SELECT
    F1.VLD_END_DATE_KST AS DT
  , F1.PRED_OUT_CNT AS PRED_OUT_CNT
--  , F2.TK_OUT_CNT AS REAL_OUT_CNT
--  , F1.PRED_OUT_CNT - F2.TK_OUT_CNT AS GAP
FROM (
    SELECT
        DATE(VLD_END_DATE AT TIME ZONE 'Asia/Seoul' + INTERVAL '1' DAY) AS VLD_END_DATE_KST
      , COUNT(DISTINCT BUY_NO) AS PRED_OUT_CNT
    FROM HADOOP_KENT.MELON_MA_STAT_PRODUCTION.F_PROD_USER_FXMT_DT  T1
    JOIN HADOOP_KENT.MELON_MA_STAT_PRODUCTION.D_PROD T2 ON (T1.PROD_ID = T2.PROD_ID)
    WHERE T1.LOG_DATE = CAST(DATE_FORMAT(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul' - INTERVAL '1' DAY, '%Y%m%d') AS VARCHAR(8))
      AND T1.PROD_STAT_CD NOT IN (3401, 3901, 2200, 2100, 3900, 3902, 3903) /*자결당일해지, 일지정지해제(자결성공), 일시정지 -> 제외*/
      AND T2.PROD_ATTR_CD NOT IN (10040, 10050) /*종량제외*/
      AND T2.PROD_SELL_PRT_CD = 60000 /*B2C*/
      AND T2.PROD_PRT_CD = 20010 /* 티켓 */
      AND T1.PF_YN = 1
      AND DATE(T1.VLD_STRT_DATE AT TIME ZONE 'Asia/Seoul') <= DATE(T1.VLD_END_DATE AT TIME ZONE 'Asia/Seoul')
      AND DATE(VLD_END_DATE AT TIME ZONE 'Asia/Seoul' + INTERVAL '1' DAY) BETWEEN DATE(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul') + INTERVAL '1' DAY AND DATE(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul') + INTERVAL '31' DAY
    GROUP BY DATE(VLD_END_DATE AT TIME ZONE 'Asia/Seoul' + INTERVAL '1' DAY)
    ) F1
--LEFT OUTER JOIN (
--    SELECT
--        DT + INTERVAL '1' DAY AS DT
--      , COUNT(IF(PROD_PRT_CD = 20010 , BUY_NO, NULL)) AS TK_OUT_CNT
--    FROM (
--        SELECT
--            DT
--          , FIRST_BUY_NO
--          , BUY_NO
--          , PROD_PRT_CD
--          , USER_MKEY AS MEMBER_KEY
--        FROM HADOOP_KENT.MELON_MA_STAT_PRODUCTION.F_PROD_USER_FXMT_DT  T1
--        JOIN HADOOP_KENT.MELON_MA_STAT_PRODUCTION.D_PROD T2 ON (T1.PROD_ID = T2.PROD_ID)
--        WHERE LOG_DATE BETWEEN DATE_FORMAT(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul' - INTERVAL '14' DAY, '%Y%m%d') AND DATE_FORMAT(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul' + INTERVAL '14' DAY, '%Y%m%d')
--          AND T1.PF_YN = 1
--          AND T1.PROD_STAT_CD NOT IN (1100, 1200, 1201, 2000, 3302, 2100, 2200, 3901, 1203, 1205, 3303)
--          AND T2.PROD_ATTR_CD NOT IN (10040, 10050)
--          AND T2.PROD_SELL_PRT_CD IN (60000)
--    ) T3
--    GROUP BY
--        DT
--) F2
--ON (F1.VLD_END_DATE_KST = F2.DT)
WHERE VLD_END_DATE_KST BETWEEN DATE(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul') + INTERVAL '1' DAY AND DATE(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Seoul') + INTERVAL '31' DAY
ORDER BY 
    F1.VLD_END_DATE_KST